### ISSUE TITLE
Multiple messages when opening for first time

### ISSUE THREAD

**Issue by marcosnz** [Xeroday/Spotify-Ad-Blocker#59]
The first time I opened the exe I got a "Please check 'Allow Spotify to be started from the Web' in your Spotify preferences." message. Fair enough. But then I got another... and another and.. one every second.

**Comment by Xeroday** [comment]
Fixed. EZBlocker will now force enable the web helper option in your Spotify settings.

**Comment by Wayward1** [comment]
Hi, I'm using the latest version of EZBlocker, and I still encounter this issue each time I start it after a reboot. FWIW, I have already had that setting enabled for a while now.
