### ISSUE TITLE
Sound ads are not blocked

### ISSUE THREAD

**Issue by Gudui** [Xeroday/Spotify-Ad-Blocker#80]
After the new Spotify update, 1.0.28. Sound ads are reintroduced. 

Is there any upcoming fix, are there new domains/ip addresses that needs to be blocked?

Thanks in advance.

**Comment by ilbonte** [comment]
I'm using Spotify 1.0.28.87.g8f9312a4 on Win10 and I don't have any issue so far. Do you have the lastest relase? https://github.com/Xeroday/Spotify-Ad-Blocker/releases

**Comment by Xeroday** [comment]
Are you sure EZBlocker is open? It will automatically close if Spotify is restarted. I've tested on W7 + W10 and it works fine.

**Comment by Gudui** [comment]
@ilbonte @Xeroday 
Yes i am sure that I have the latest version and that EZBlocker is running.
It still mutes the sound ads(as i can see is implemented in the source code), but it doesn't total block them as before.

**Comment by ilbonte** [comment]
Maybe there are some location-based ads that are not filtered? May I ask where are you from?

**Comment by Gudui** [comment]
Denmark, everyone else i know, from Denmark, who have been using this application without any problems also expire sound ads.

Anything i can do to help?

**Comment by Xeroday** [comment]
Can you copy and paste what's in your host file? It's located in C:\Windows\System32\drivers\etc\hosts. You can open it up with Notepad.

**Comment by Gudui** [comment]
@Xeroday 
I have the following in my hosts file. 
0.0.0.0 pubads.g.doubleclick.net
0.0.0.0 securepubads.g.doubleclick.net
0.0.0.0 www.googletagservices.com
0.0.0.0 gads.pubmatic.com

Should correspond exactly to the newest version of Ezblocker. https://github.com/Xeroday/Spotify-Ad-Blocker/blob/master/EZBlocker/EZBlocker/Form1.cs#L32


Thanks in advance

**Comment by Burpomatic** [comment]
I'm experiencing the same issues as Gudui (ads are muted, but not skipped like they used to a few days ago). I live in Canada, running windows 7, spotify 1.0.28.87.g8f9312a4, EZBlocker 1.6.5, same content as Gudui in my hosts file. Any other information I could share to help you track the problem?

**Comment by Gudui** [comment]
I've installed CurrPorts and i've tried to listen for hosts from the Spotify client. When the ads come up, the following addresses has been shown as 'new' in the monitor.

`
ee-in-f95.1.e100.net
on3-weblb-wg2.lon3.spotify.com
lon3-weblb-wg3.lon3.spotify.com
sto3-weblb-wg4.sto3.spotify.com
`
Seems like they have a lot of domains for sending ads.. I'll catch the ips next time

**Comment by Raditude** [comment]
I am also experiencing the same issue. I'm from the US and I'm running Spotify on windows 10. I just updated EzBlocker to the latest version as well. I've also noticed there are banner ads at the bottom too, for the most part nothing loads in there but I've never seen them there before while using EzBlocker.

**Comment by agonarg** [comment]
Hi, I am also getting all the visual ads, though the sound ones get muted. It is due to the latest Spotify update I'm afraid. I created an issue but then I bumped into this thread and closed it (sorry!).

Thanks for this amazing program though.

**Comment by agonarg** [comment]
Adding...

> ee-in-f95.1.e100.net
> on3-weblb-wg2.lon3.spotify.com
> lon3-weblb-wg3.lon3.spotify.com
> sto3-weblb-wg4.sto3.spotify.com

...to the host file on 0.0.0.0 IPs made it better, no more visual ads are popping up. Except the sound ones which now seem to enter MUTED compared to previous versions which were skipping them perfectly.

Still great workaround as of today. Thanks.

**Comment by Xeroday** [comment]
Latest version should be working. Tested on Win 7/10 in USA. Audio + banner ad blocking is technically still experimental.

**Comment by GermanCoding** [comment]
Still not blocking (audio + banner + video) on the latest EZBlocker version (1.6.6.0) in Germany even though I cleared the complete cache to force a re-download of possible cached ads. Looks like the have some new ad servers, I made a quick investigation with Wireshark and my suspection is that Spotify is now able to download ads directly from the "access point" servers where also the main connection is running.

**Comment by Gudui** [comment]
I'm experiencing the exact same as @GermanCoding 
@Xeroday Please don't close this issue, people around the world are having issues.

**Comment by Xeroday** [comment]
It's very time-consuming to find ad hosts, especially if they are region dependent and are potentially served from the same hosts/IPs as regular content. EZBlocker will always fall back to muting the ads, which was the original intent of the program. 

That being said, could you guys try 1.6.6.2, which blocks a new host.

**Comment by GermanCoding** [comment]
Thank you Xeroday! The change you made in the HOSTS file match with the changes I made locally in my file (altough I added a few more hosts and made a redirect not only to localhost but also to real webservers which respond to Spotify's HTTP requests to confuse Spotify's ad-finding algorithm). Now ads are totally blocked again for me.

I know the "block all ads" function is not the main feature of this program, but for many users it's the most important feature (the blog comments suggest that), so thank you for re-opening the issue.

**Comment by Gudui** [comment]
@Xeroday Totally understandable. I'll help sniffing ads address received from Denmark.

**Comment by agonarg** [comment]
Latest v1.6.7.0 working flawlessly in Spain now. Thanks for the update.

**Comment by CHEF-KOCH** [comment]
Another stuff may needs to be added:
> 0.0.0.0 151.101.12.246 (This is over Port 80) 

Mostly if I use Spotify it communicates over other ports and addresses. like <code>sjc1-accesspoint-a23.sjc1.spotify.com</code>

**Comment by GermanCoding** [comment]
I had a report today from a friend that since the Spotify update 1.0.29.92.g67727800 ads are played again. I will do my best to search for the new hosts.

**Comment by CHEF-KOCH** [comment]
wouldn't it be easier to only allow ip's/domains instead of blocking the ones which  may showing ads? This would also prevent new annoying ads on newer versions, since only the once are allowed which are on the whitelist. But I'm sure if you inject Spotify.exe/SpotifyWebHelper.exe some AV's may detect is as trojan. 

The problem with hosts is that it may not work on ssl (if Spotify comes/uses it's own create to prevent such blocking).

**Comment by GermanCoding** [comment]
@CHEF-KOCH Why should it not work with SSL? Spotify already uses a mixture of HTTP/HTTPS and some own protocol for data transfer. The blocklist EZBlocker provides is just an entry in the HOSTS-file of the OS. This prevents the OS from resolving the domain names of Spotify's ad servers to IP addresses by redirecting them all to localhost. This method blocks all traffic, independent from the protocol. However, it is indeed very easy to create an algorithm to detect such blocking and some day the developers of Spotify might fix it. The HOSTS file itself is designed as a blacklist (or more exactly: as a filter), not as a whitelist.

**Comment by JohnTheGr8** [comment]
It has been almost a month without a good solution (I tried myself but got frustrated and gave up after 20+ sub-domains) so here's simple workaround for the time being:
- Downgrade to version 1.0.27 (you'll have to download the setup from a third-party website)
- Add `0.0.0.0 upgrade.spotify.com` to your hosts file to block Spotify from auto-upgrading

and everything is back to how it used to be. I am not sure about version 1.0.29, but 1.0.28 didn't seem to have anything added apart from the dreadful ads.

Cheers

**Comment by CHEF-KOCH** [comment]
This is not correct what you've said. 
If you use another DNS system the hosts file get's ignored, same if a product uses it's own certificate to redirect/tunnel the traffic. See also [here](http://serverfault.com/questions/95036/what-can-cause-a-dns-lookup-to-ignore-a-hosts-file-entry), [here](http://www.infoworld.com/article/2641599/security/microsoft-hosts-file-bypass-issue.html), [here]( https://social.msdn.microsoft.com/Forums/vstudio/en-US/e141eec1-f60d-46cb-b505-06514e032b4a/action?threadDisplayName=vstudio&forum=vcgeneral) & [here](https://stackoverflow.com/questions/17315385/dns-lookup-and-http-proxies). In other words Spotify could simply use a proxy/socks to bypass it but from what I know they currently not doing it.

Well my Whitelist idea would solve a lot of problems because you could add it and for longer time not care about it. I know it's difficult to implement - I do agree.
